### ISSUE TITLE
Ошибка при записи в базу

### ISSUE THREAD

**Issue by rkinwork** [madiedinro/simple-clickhouse#1]
Нашел ошибку при исполнении кода

```Python
for i in range(1, 2001):
    ch.push('my_table', {'name': 'hux', 'num': i})

ch.flush('my_table')
```
 Если в буфере не остается остатка, то выдается ошибка метод   __make_query заменяет метод вставки на GET, а по документации Clickhouse 

> When using the GET method, 'readonly' is set. In other words, for queries that modify data, you can only use the POST method. You can send the query itself either in the POST body, or in the URL parameter.

Как воспроизвести ошибку:
Попробовать залить массив строк размером кратным значению буфера.
Если буфер равен 1000, то массив строк должен быть 1000 или 2000 строк

**Comment by madiedinro** [comment]
fixed
