### ISSUE TITLE
Не работает вставка данных с русскими символами 

### ISSUE THREAD

**Issue by rkinwork** [madiedinro/simple-clickhouse#2]
Версия 4, Python 3.6

```
d = {'key': 'пользователь'}
conn.push('table_name', d)
conn.flush('table_name')
```

Выдает ошибку 

> UnicodeEncodeError: 'latin-1' codec can't encode characters in position 8-19: Body ('пользователь') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.

UPD:
Добавил версию Python

**Comment by madiedinro** [comment]
А python какой версии?

**Comment by rkinwork** [comment]
python 3.6

**Comment by madiedinro** [comment]
fixed
